/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcertoRouteImport } from './routes/acerto'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ErroRouteImport } from './routes/erro'
import { Route as HomeRouteImport } from './routes/home'
import { Route as PerguntaRouteImport } from './routes/pergunta'
import { Route as RegrasRouteImport } from './routes/regras'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcertoRoute = AcertoRouteImport.update({
  id: '/acerto',
  path: '/acerto',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ErroRoute = ErroRouteImport.update({
  id: '/erro',
  path: '/erro',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const PerguntaRoute = PerguntaRouteImport.update({
  id: '/pergunta',
  path: '/pergunta',
  getParentRoute: () => rootRouteImport,
} as any)
const RegrasRoute = RegrasRouteImport.update({
  id: '/regras',
  path: '/regras',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acerto': typeof AcertoRoute
  '/cadastro': typeof CadastroRoute
  '/erro': typeof ErroRoute
  '/home': typeof HomeRoute
  '/pergunta': typeof PerguntaRoute
  '/regras': typeof RegrasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acerto': typeof AcertoRoute
  '/cadastro': typeof CadastroRoute
  '/erro': typeof ErroRoute
  '/home': typeof HomeRoute
  '/pergunta': typeof PerguntaRoute
  '/regras': typeof RegrasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acerto': typeof AcertoRoute
  '/cadastro': typeof CadastroRoute
  '/erro': typeof ErroRoute
  '/home': typeof HomeRoute
  '/pergunta': typeof PerguntaRoute
  '/regras': typeof RegrasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/acerto' | '/cadastro' | '/erro' | '/home' | '/pergunta' | '/regras'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/acerto' | '/cadastro' | '/erro' | '/home' | '/pergunta' | '/regras'
  id:
    | '__root__'
    | '/'
    | '/acerto'
    | '/cadastro'
    | '/erro'
    | '/home'
    | '/pergunta'
    | '/regras'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcertoRoute: typeof AcertoRoute
  CadastroRoute: typeof CadastroRoute
  ErroRoute: typeof ErroRoute
  HomeRoute: typeof HomeRoute
  PerguntaRoute: typeof PerguntaRoute
  RegrasRoute: typeof RegrasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acerto': {
      id: '/acerto'
      path: '/acerto'
      fullPath: '/acerto'
      preLoaderRoute: typeof AcertoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erro': {
      id: '/erro'
      path: '/erro'
      fullPath: '/erro'
      preLoaderRoute: typeof ErroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pergunta': {
      id: '/pergunta'
      path: '/pergunta'
      fullPath: '/pergunta'
      preLoaderRoute: typeof PerguntaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regras': {
      id: '/regras'
      path: '/regras'
      fullPath: '/regras'
      preLoaderRoute: typeof RegrasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcertoRoute: AcertoRoute,
  CadastroRoute: CadastroRoute,
  ErroRoute: ErroRoute,
  HomeRoute: HomeRoute,
  PerguntaRoute: PerguntaRoute,
  RegrasRoute: RegrasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
